### ISSUE TITLE
Need to be able to update rfid tag 'secret' values.

### ISSUE THREAD

**Issue by brackendawson** [members-area/members-area#53]
If I implement somakeit/door-controller2#20 then the post request that updates count, may instead update secrets to disable a tag.

It's possible that the members area will handle this already, but I want to check.

**Comment by benjie** [comment]
Yeah; we don't seem to handle that currently - at the moment we only store secrets on create.

https://github.com/members-area/members-area/blob/255f101a42fc57eb970f5f2e4610855f5a0d4a14/plugins/members-area-rfid-tags/controllers/rfid-tags.coffee#L45-L87

@brackendawson Perhaps a simpler alternative would be to just bump the count to an unobtainably high value? That's also easier to remedy than deleting data if something were to go wrong.

**Comment by brackendawson** [comment]
@benjie as the count is circular, there's no such concept of a very high number.

I considered that you can't undo it to be a feature, prevent people just going "oh it does that, let me just reset it again."

We can stay as we are while considering this, but if someone's tag got flagged as duplicate and they couldn't use it to get in, we'd have to manually remove it from the database to blacklist the cloned one.

**Comment by benjie** [comment]
Should be easy to fix; just need to add something like

```coffee
            secrets = Object.assign({}, tag.secrets)
            for k, v of remoteTag when k.match /^sector_/
              secrets[k] = v
            tag.secrets = secrets
```


around here

https://github.com/members-area/members-area/blob/255f101a42fc57eb970f5f2e4610855f5a0d4a14/plugins/members-area-rfid-tags/controllers/rfid-tags.coffee#L65

It's a shame the count can't be used since that seemed a simple solution, but you're right of course the circular-ness messes it up.

:warning: WARNING: not sure our version of Node supports `Object.assign`; safer to use `_.clone` if we have underscore/lodash. Also probably ought to only overwrite if something was actually changed. And maybe log that it was changed for an audit trail - a console.log should be sufficient

**Comment by brackendawson** [comment]
We could also add a blacklisted field if you'd like a back-out option.

**Comment by benjie** [comment]
I just wrote

> I just wrote
> 
> > Nah, you seem confident that it should work and we've had no false positives so far.
> 
> But actually, perhaps it would be worth adding because that'd be easy to then surface in the tag list on the admin side with big-ass warning signs and what not.

But actually the likelyhood of that happening is quite low, so I'm back to my initial thought: "Nah"

Let's just invoke YAGNI and do the fix above for now. If we ever notice a card being disabled then we should build code to surface that better.
